"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { theme } from '@/style/Theme'
import { GlobalStyles } from '@/style/Global'
import { ThemeProvider, styled } from 'styled-components'
import SideBar from '@/src/scenes/SideBar/SideBar'
import WhoFollow from '@/src/scenes/WhoFollow/WhoFollow'



// const inter = Inter({ subsets: ['latin'] })
import StyledComponentsRegistry from '@/lib/registry'
import NavBar from '@/src/scenes/NavBar/NavBar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const ChildrenWrapper = styled.div`
  flex: 1;
`

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Roboto Condensed */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400&display=swap" rel="stylesheet" />

        {/* Inter */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500&display=swap" rel="stylesheet" />

        {/* Roboto */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
      </head>
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme}>
            <GlobalStyles />
            <NavBar />
            <div style={{ display: 'flex', width: "100%" }}>
              <SideBar />
              <ChildrenWrapper>
                {children}
              </ChildrenWrapper>
              <WhoFollow />
            </div>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>

  )
}
